import type { BrowseCategory } from "@/lib/site-data";
import type { EducationLevel } from "@/lib/video-classification";

export type YouTubeChannelSource = {
  key: string;
  name: string;
  channelId: string;
  defaultCategory: BrowseCategory;
  allowedCategories: BrowseCategory[];
  displayDescription: string;
  strengths: string[];
  learningStyle: "visual" | "conceptual" | "technical" | "fast-paced" | "structured";
  difficultyBias: "beginner" | "mixed" | "advanced";
  bestFor: string;
  categoryKeywords?: Partial<Record<BrowseCategory, string[]>>;
  educationLevel?: EducationLevel;
  language?: string;
  maxResults?: number;
  pages?: number;
};

export const youtubeChannels: YouTubeChannelSource[] = [
  {
    key: "veritasium",
    name: "Veritasium",
    channelId: "UCHnyfMqiRRG1u-2MsSQLbXA",
    defaultCategory: "Physics",
    allowedCategories: ["Physics", "Science", "Mathematics"],
    displayDescription: "Experimental, curiosity-led explanations that make physical intuition feel concrete.",
    strengths: ["Quantum", "Mechanics", "Engineering"],
    learningStyle: "conceptual",
    difficultyBias: "mixed",
    bestFor: "Deep experimental physics explanations",
    categoryKeywords: {
      Physics: ["physics", "quantum", "space", "mechanics", "experiment", "engineering"],
      Science: ["science", "biology", "chemistry"],
      Mathematics: ["math", "theorem", "proof"],
    },
    educationLevel: "college",
    maxResults: 10,
    pages: 3,
  },
  {
    key: "3blue1brown",
    name: "3Blue1Brown",
    channelId: "UCYO_jab_esuFRV4b17AJtAw",
    defaultCategory: "Mathematics",
    allowedCategories: ["Mathematics", "Physics", "AI & Tech", "Science"],
    displayDescription: "Visual mathematical storytelling that turns abstract ideas into something you can see.",
    strengths: ["Calculus", "Geometry", "Logic"],
    learningStyle: "visual",
    difficultyBias: "mixed",
    bestFor: "Visual explanations of advanced math ideas",
    categoryKeywords: {
      Mathematics: ["math", "mathematics", "proof", "geometry", "calculus", "algebra", "theorem"],
      Physics: ["physics", "mechanics", "laplace", "quantum"],
      "AI & Tech": ["ai", "neural network", "machine learning"],
      Science: ["biology", "bacteria"],
    },
    educationLevel: "college",
    maxResults: 10,
    pages: 3,
  },
  {
    key: "two-minute-papers",
    name: "Two Minute Papers",
    channelId: "UCbfYPyITQ-7l4upoX8nvctg",
    defaultCategory: "AI & Tech",
    allowedCategories: ["AI & Tech", "Physics", "Science", "Mathematics"],
    displayDescription: "Fast research summaries focused on what is new, important, and worth understanding in AI.",
    strengths: ["LLMs", "Computer Vision", "Semiconductors"],
    learningStyle: "fast-paced",
    difficultyBias: "mixed",
    bestFor: "Cutting-edge AI research summaries",
    categoryKeywords: {
      "AI & Tech": ["ai", "neural", "rendering", "simulation", "nvidia", "model"],
      Physics: ["physics", "simulation", "cloth", "fluids", "engine"],
      Mathematics: ["equation", "optimization", "geometry"],
      Science: ["medical", "brain", "research"],
    },
    educationLevel: "general",
    maxResults: 10,
    pages: 3,
  },
  {
    key: "kurzgesagt",
    name: "Kurzgesagt",
    channelId: "UCsXVk37bltHxD1rDPwtNM8Q",
    defaultCategory: "Science",
    allowedCategories: ["Science", "Physics"],
    displayDescription: "Highly visual conceptual storytelling for big science questions and long-horizon thinking.",
    strengths: ["Climate", "Biology", "Astrophysics"],
    learningStyle: "visual",
    difficultyBias: "beginner",
    bestFor: "Visual explanations of complex science concepts",
    categoryKeywords: {
      Science: ["biology", "medicine", "planet", "brain", "cells", "evolution"],
      Physics: ["space", "black hole", "planet", "universe"],
    },
    educationLevel: "general",
    maxResults: 10,
    pages: 3,
  },
  {
    key: "scishow",
    name: "SciShow",
    channelId: "UCZYTClx2T1of7BRZ86-8fow",
    defaultCategory: "Science",
    allowedCategories: ["Science"],
    displayDescription: "Broad science explainers that make current research feel approachable without losing substance.",
    strengths: ["Biology", "Chemistry", "Medicine"],
    learningStyle: "structured",
    difficultyBias: "beginner",
    bestFor: "Clear entry points into broad science topics",
    categoryKeywords: {
      Science: ["biology", "chemistry", "medicine", "science", "research"],
    },
    educationLevel: "general",
    maxResults: 10,
    pages: 3,
  },
  {
    key: "crash-course",
    name: "CrashCourse",
    channelId: "UCX6b17PVsYBQ0ip5gyeme-Q",
    defaultCategory: "Science",
    allowedCategories: ["Science", "Mathematics", "Physics", "AI & Tech"],
    displayDescription: "Structured course-style teaching with strong sequencing and reliable educational framing.",
    strengths: ["Biology", "Chemistry", "Computer Science"],
    learningStyle: "structured",
    difficultyBias: "beginner",
    bestFor: "Course-like introductions that build foundations quickly",
    categoryKeywords: {
      Science: ["biology", "chemistry", "ecology", "climate", "anatomy", "medicine"],
      Mathematics: ["algebra", "calculus", "statistics"],
      Physics: ["physics", "space", "engineering"],
      "AI & Tech": ["computer science", "ai", "technology"],
    },
    educationLevel: "high-school",
    maxResults: 8,
    pages: 2,
  },
  {
    key: "amoeba-sisters",
    name: "Amoeba Sisters",
    channelId: "UCCemjNPpJYhGDgaEqeeA4HA",
    defaultCategory: "Science",
    allowedCategories: ["Science"],
    displayDescription: "Friendly visual biology teaching built for fast conceptual understanding.",
    strengths: ["Biology", "Genetics", "Cells"],
    learningStyle: "visual",
    difficultyBias: "beginner",
    bestFor: "Accessible biology foundations",
    categoryKeywords: {
      Science: ["biology", "cells", "genetics", "dna", "ecology", "evolution"],
    },
    educationLevel: "middle-school",
    maxResults: 8,
    pages: 2,
  },
  {
    key: "osmosis",
    name: "Osmosis from Elsevier",
    channelId: "UCNI0qOojpkhsUtaQ4_2NUhQ",
    defaultCategory: "Science",
    allowedCategories: ["Science"],
    displayDescription: "Medical teaching with disciplined explanations, diagrams, and clinically grounded concepts.",
    strengths: ["Medicine", "Anatomy", "Physiology"],
    learningStyle: "technical",
    difficultyBias: "advanced",
    bestFor: "Serious medicine and physiology explanations",
    categoryKeywords: {
      Science: ["medicine", "medical", "anatomy", "physiology", "pathology", "immunology", "disease"],
    },
    educationLevel: "college",
    maxResults: 8,
    pages: 2,
  },
  {
    key: "minute-earth",
    name: "MinuteEarth",
    channelId: "UCeiYXex_fwgYDonaTcSIk6w",
    defaultCategory: "Science",
    allowedCategories: ["Science", "Physics"],
    displayDescription: "Short conceptual explainers that connect climate, ecology, and planetary systems cleanly.",
    strengths: ["Climate", "Ecology", "Earth Systems"],
    learningStyle: "conceptual",
    difficultyBias: "beginner",
    bestFor: "Climate and earth-science intuition",
    categoryKeywords: {
      Science: ["climate", "ecology", "biology", "earth", "ocean", "environment"],
      Physics: ["planet", "space", "energy"],
    },
    educationLevel: "general",
    maxResults: 8,
    pages: 2,
  },
  {
    key: "nile-red",
    name: "NileRed",
    channelId: "UCFhXFikryT4aFcLkLw2LBLA",
    defaultCategory: "Science",
    allowedCategories: ["Science"],
    displayDescription: "Hands-on chemistry demonstrations that show how reactions and materials behave in practice.",
    strengths: ["Chemistry", "Molecules", "Reactions"],
    learningStyle: "technical",
    difficultyBias: "mixed",
    bestFor: "Applied chemistry and reaction-focused learning",
    categoryKeywords: {
      Science: ["chemistry", "chemical", "reaction", "compound", "molecule", "synthesis"],
    },
    educationLevel: "college",
    maxResults: 8,
    pages: 2,
  },
  {
    key: "practical-engineering",
    name: "Practical Engineering",
    channelId: "UCMOqf8ab-42UUQIdVoKwjlQ",
    defaultCategory: "Physics",
    allowedCategories: ["Physics", "Science", "AI & Tech"],
    displayDescription: "Concrete engineering explanations focused on systems, infrastructure, and physical tradeoffs.",
    strengths: ["Engineering", "Mechanics", "Energy"],
    learningStyle: "structured",
    difficultyBias: "mixed",
    bestFor: "Real-world engineering explanations",
    categoryKeywords: {
      Physics: ["engineering", "mechanics", "energy", "structural", "hydraulics", "electricity"],
      Science: ["water", "environment", "materials", "climate resilience"],
      "AI & Tech": ["automation", "control systems", "infrastructure technology"],
    },
    educationLevel: "college",
    maxResults: 8,
    pages: 2,
  },
];
